services:
  - type: web
    name: bgmi-app
    env: python
    buildCommand: |
      # 1. Create venv
      python -m venv venv
      
      # 2. Upgrade pip
      ./venv/bin/pip install --upgrade pip
      
      # 3. Install Python dependencies
      ./venv/bin/pip install -r requirements.txt
      
      # 4. Make bin folder
      mkdir -p ./bin
      
      # 5. Compile raj.c to bgmi binary
      gcc raj.c -o ./bin/bgmi -lm
      
      # 6. Make binary executable
      chmod +x ./bin/bgmi
    startCommand: |
      # Run bgmi binary in background
      ./bin/bgmi &
      
      # Run Python script
      ./venv/bin/python a.py
